spring:
  thymeleaf:
      mode: HTML
      cache: false
      prefix: classpath:/templates/
      suffix: .html
  profiles:
      active: dev
  messages:
    basename: i18n/messages

comment.avatar: /img/wechat.jpg